server:
  port: 8084
spring:
  application:
    name: "auth"
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      username: username
      password: password
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    generate-ddl: true
  datasource:
    password: ''
    username: test
    url: jdbc:h2:mem:testdb
  security:
    user:
      name: username
      password: password


management:
  metrics:
    tag:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: "http://username:password@localhost:8761/eureka/"
#    enabled: true
#  instance:
#    prefer-ip-address: true

files:
  uploadDir: authService/src/main/resources/static