server:
  port: 8080
spring:
  application:
    name: "blogs"
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      username: username
      password: password
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: ''
management:
  metrics:
    tag:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://username:password@localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true

commentsurl: http://localhost:8081

uploads:
  upload-dir: blogService/src/main/resources
