server:
  port: 8083
spring:
  application:
    name: "messages"
  config:
    import: optional:configserver:http://localhost:8888/
  cloud:
    config:
      username: username
      password: password
  profiles:
    active: default
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    show-sql: false
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    password: ''
    username: testdb
    url: jdbc:h2:mem:testdb



management:
  metrics:
    tag:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://username:password@localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
